/*
this code is terrible on purpose.
it's meant to stress test syntax highlighting
It is syntactically valid query
        Foo.bar( , )
            Table.List( Tbar.Casdf(...) )
    )
see more: <https://github.com/microsoft/vscode-extension-samples/tree/main/semantic-tokens-sample>
    */
let
    T.Wfd = List.Count = q = e = 3,
    l  = TA.A.Wfd(),
    l3 = T.Wfd(),
    l7 = T.Aa(),
    l9 = T.Aaf(),
    l2 = TA.AWfd(),
    T.L.P = List.Count,
    j = T.L(...), q = T.L.P( ),
    q1 = #"List."( each 0, each _ < 1, each _ ),
    z = table.list(df),
    #"TA.A.Wfd" = "#(cr,lf)#""Table.List(""",
    #" Table.List(bar Table.List({3,45,5}))" = 345,
    a = Table.List,
    b = Table(),
    now = #duration(0,0,0,1), t = #table( type table[ Id = Int64.Type, Nested = Table.Type], {} ),
    r = Table.Combine({null, #"Some.Stepame"( ... ) }),
    r2 = Table.Combine(
        {null, #"Some.Stepame"( ... ) }
    ),
    r3 = {null, #"Some.Stepame"( ... ) }, // #"Table.List"#".List",
    #"[ T.Bar(" = [ fd = List.Bar( List.Transform( {9..4}, each _ + 3 )), When = DateTime.FixedLocalNow() ],
    // c = List.Generate(...) ],
    zed = List.Transform( source, (item) => item * 3 ) + Bar.FromText( " Table.List(" & ".." ),
    /*
        Text.Type, TA.A.Wfd,
        Text.Type
        */
    q3 = foo.bar(sdf),
    #"q35" = Bcat( { 234 } ),
    z2 = Bcat(),
    g = Table.Bar(dsf)


in [g=Table.RowCount( #table(null, {{null}}))]