[ HSL Hue from Sales ] = 
    // simpler version, which scales hue from 0 degrees to maxHue
    // outputs a gradient like: 
        // hsl(   0, 80%, 78%) 
        // hsl(  40, 80%, 78%) 
        // hsl( 160, 80%, 78%)
    var maxHue = 160

    // Can this ALL() be rewritten to run faster? 
    VAR CurrentValue = SELECTEDVALUE( Sale[Value], 0 )
    VAR MinValue     = CALCULATE( MIN(Sale[Value]), All( Sale[Value] ) )  
    VAR MaxValue     = CALCULATE( MAX(Sale[Value]), All( Sale[Value] ) )
    
    var relativeValue = 
        DIVIDE(
            CurrentValue - MinValue,
            MaxValue - MinValue, 
            0 
        )

    // outputs the color string: "hsl( 60, 80%, 78% )"
    var renderInt  = format( (relativeValue * maxHue), "#,0", "en-us" )
    var finalColor = "hsl( " & renderInt & ", 80%, 80%)"
    return finalColor
